name: pet_adoption_app
description: Pet Adoption app by @Yavnik.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  get_it: ^7.6.0
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  slide_to_act: ^2.0.1
  confetti: ^0.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  bloc_test: ^9.1.3
  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.5

flutter:
  uses-material-design: true

  assets:
    - assets/